global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ml_model'
    static_configs:
      # For locally run prometheus
      # - targets: ['127.0.0.1:8000']  
      - targets: ['host.docker.internal:8000']